image: alpine/edge
packages:
  - npm
sources:
  - https://git.sr.ht/~ledge/ng-app
tasks:
  - install: |
      cd ng-app
      npx npm@7 install
  - test: |
      cd ng-app
      npx -p node@8 npm test
      npx -p node@10 npm test
      npx -p node@12 npm test
      npx -p node@14 npm test
      npx -p node@15 npm test
